### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by MackoLysy** [matthiasbock/Raspberry-Pi-SPI-slave#1]
Hello.
Can you refresh link how to set this code?

**Comment by matthiasbock** [comment]
I assume, you're refering to the link http://tylernichols.me/raspberry-pi-bare-metal-spi-slave/. I quickly tested it and you're right, the page doesn't seam to be reachable anymore. The domain is still online, but he now apparently uses Redmine. 

Could you try to get in touch with the guy and ask him for an updated link, please?

**Comment by matthiasbock** [comment]
@peterfortress Your post is off-topic. Please open a new issue for your problem.

**Comment by ehsunmotamedi** [comment]
Hi @matthiasbock 
i just got "Segmentation fault" error 
can you help me debug this?!?!

**Comment by matthiasbock** [comment]
@SyberSprit Your post is off-topic. Please open a new issue for your problem. Also, if you want anyone to be able to help you, you need to provide details about what exactly you did, what you expected to happen and what happened instead.

**Comment by peterfortress** [comment]
> Hi @matthiasbock
> i just got "Segmentation fault" error
> can you help me debug this?!?!

----------

you can code here: I useit and it works:
https://github.com/offis/raspi-directhw/issues/1#event-2103516196

**Comment by cheddarzao** [comment]
Hello. The link isn't available. Can you provide the one that works?

**Comment by matthiasbock** [comment]
Please read my previous comments above. I am not the author of the site in question.

As a hint, the Internet Archive has a backup of the site from 2015:
https://web.archive.org/web/20160319142430/http://tylernichols.me/raspberry-pi-bare-metal-spi-slave/
